### ISSUE TITLE
Script crashes on password with extended ASCII passwords

### ISSUE THREAD

**Issue by Cieper** [fopina/kdbxpasswordpwned#3]
I generated a password using KeePassXC's password generator, and enabled the "Extended ASCII" option, generating the following password:

```
`²¢D\=X\NÉZ¯Ú;"IøUü6-}¼#à~A¿»Öcã1s(½:ðâ~rÕnY®Ü[¥Ý!=_4«÷ÜÕ¾ý;(ßcò5]ßÔ"çÛ1áý1Mj9æxRÙ~|kf<%Ô5¼Å5xçkZ/`a\ÛFßÜ¡ÈÞ{ÌG=vD¾ÀÏa´aãÖ6ØÊFLv
```

When scanning the passwords this causes the program to crash, with either of the following crashes, depending upon the exact password used:

```
Traceback (most recent call last):
  File "/home/cieper/bin/kdbxpasswordpwned.py", line 51, in <module>
    main()
  File "/home/cieper/bin/kdbxpasswordpwned.py", line 40, in main
    r = check_hash(kv['Password'])
  File "/home/cieper/bin/kdbxpasswordpwned.py", line 22, in check_hash
    h = hashlib.sha1(password).hexdigest().upper()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf7' in position 1: ordinal not in range(128)
```

```
Traceback (most recent call last):
  File "/home/cieper/bin/kdbxpasswordpwned.py", line 51, in <module>
    main()
  File "/home/cieper/bin/kdbxpasswordpwned.py", line 40, in main
    r = check_hash(kv['Password'])
  File "/home/cieper/bin/kdbxpasswordpwned.py", line 22, in check_hash
    h = hashlib.sha1(password).hexdigest().upper()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
```

**Comment by fopina** [comment]
could you share a kdbx in that tool with such password and share it so I can include it in the tests? just a single entry so it's small :)

**Comment by Cieper** [comment]
Sure thing, I attached [extended-ascii.kdbx.zip](https://github.com/fopina/kdbxpasswordpwned/files/2790919/extended-ascii.kdbx.zip). The password required for the file is 'extended-ascii'

**Comment by fopina** [comment]
Should be fixed now (in master and in `dev` docker tag), thanks for reporting!
